# Generated by Django 5.0 on 2026-01-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(upload_to='originals/')),
                ('processed_image', models.ImageField(blank=True, null=True, upload_to='processed/')),
                ('background_type', models.CharField(choices=[('color', 'Color'), ('image', 'Image')], max_length=20)),
                ('background_value', models.TextField()),
                ('model_used', models.CharField(choices=[('isnet', 'ISNet'), ('bria', 'BRIA RMBG')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('file_size', models.BigIntegerField()),
                ('width', models.IntegerField(null=True)),
                ('height', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
